# Generated by Django 3.0.8 on 2020-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200706_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
