# Generated by Django 3.0.8 on 2020-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200706_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(default='cpros003@fiu.edu'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.TextField(default='Carlos Prosopio', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.TextField(default='(786) 234 - 8413'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(default='Web Dev - IT Tech - DB Programmer', max_length=200),
        ),
    ]
