# Generated by Django 3.0.8 on 2020-07-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200706_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(default='Carlos Prosopio'),
        ),
    ]
